### ISSUE TITLE
The TODO workflow is unable to push changes

### ISSUE THREAD

**Issue by oddstr13** [EventAccess/django-app-database#10]
Investigate why this is.
- [ ] Are branch protection rules OK?
- [ ] Is the workflow receiving secrets properly?
- [ ] Are we missing the default GitHub action secret?

What is the difference from the Meta repo, except from the fact that we are using a sub-workflow, what's wrong here?

**Comment by oddstr13** [comment]
This is also likely affecting BackendAPI, we just haven't hit it yet

**Comment by oddstr13** [comment]
Disabled the backlink generation rather than fixing, good enough for now
